avatar_size: 80
category:
  per_page: 7
  per_word: 5
user:
  per_page: 7
  avatar_size: 50
admin:
  words:
    per_page: 10
    default_size_word_answers: 4
word_filter: {learned: "learned", not_learned: "not_learned", all: "show_all"}
filter_word: [".learned", ".not_learned"]
word:
  per_page: 10
